---
name: test
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.3'
    - run: go version
    - run: go mod download
    - run: go test -v ./... -race -covermode=atomic
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.39
